name: Hello World
run-name: ${{ github.actor }} - says hello world on ${{ github.ref_name }} 🚀
on: [workflow_dispatch]

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Run kotlin script
        uses: fwilhe2/setup-kotlin@main
        with:
          script: |
              #!/usr/bin/env kotlin
              println("hello world!")
