name: Hello World
run-name: ${{ github.actor }} - says hello world on ${{ github.ref_name }} 🚀
on: [workflow_dispatch]
  
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: set variavle in shell
        run: |
          echo "version=5.67.0" >> $GITHUB_ENV
          
      - name: Run kotlin script
        uses: fwilhe2/setup-kotlin@main
        with:
          script: |
              #!/usr/bin/env kotlin
              println("hello world!")
              println("version ${{ env.version }}")
              "BODY=this is body from kotlin" >> $GITHUB_ENV
              
      - name: get variavle in shell
        run: |
          echo "version: ${{ env.version }}"
          echo "body: ${{ env.BODY }}"
