name: Hello World
run-name: ${{ github.actor }} - says hello world on ${{ github.ref_name }} 🚀
on: [workflow_dispatch]

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Run kotlin script
        run: |
           #!/usr/bin/env kotlin
           println("Hello World!)
